import { Plus_Jakarta_Sans } from 'next/font/google'; // Importer la police Plus Jakarta Sans
import './globals.css';
import Footer from './components/footer';

// Appliquer la police Plus Jakarta Sans avec une variable CSS
const plusJakartaSans = Plus_Jakarta_Sans({
    variable: '--font-plus-jakarta-sans',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={`${plusJakartaSans.variable} antialiased`}>
        {children}
        <Footer />
        </body>
        </html>
    );
}
